apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: pubsub-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pubsub-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.signadot.com/inject: "true"
    spec:
      serviceAccountName: frontend
      enableServiceLinks: false
      containers:
        - name: frontend
          image: signadot/pubsub-demo:latest
          command:
            - "npm"
            - "run"
            - "frontend"
          env:
            - name: FRONTEND_PORT
              value: "40000"
            - name: BASELINE_NAME
              value: "frontend"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 40000
          securityContext:
            # Run with the "node" user
            runAsUser: 1000
            runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pubsub-demo
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 4000
      targetPort: 40000
      name: http
